version: '3.8'

services:
  postgres_container:
    image: postgres:15-alpine
    container_name: postgres_nfl_t6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: touchdown123
      POSTGRES_DB: superbowl_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: